// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.findyourjob.domain;

import es.uca.iw.findyourjob.domain.Empresa;
import es.uca.iw.findyourjob.domain.EmpresaDataOnDemand;
import es.uca.iw.findyourjob.domain.Localizacion;
import es.uca.iw.findyourjob.domain.LocalizacionDataOnDemand;
import es.uca.iw.findyourjob.domain.Oferta;
import es.uca.iw.findyourjob.domain.OfertaDataOnDemand;
import es.uca.iw.findyourjob.domain.PuestoDataOnDemand;
import es.uca.iw.reference.OfertaEstado;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OfertaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OfertaDataOnDemand: @Component;
    
    private Random OfertaDataOnDemand.rnd = new SecureRandom();
    
    private List<Oferta> OfertaDataOnDemand.data;
    
    @Autowired
    EmpresaDataOnDemand OfertaDataOnDemand.empresaDataOnDemand;
    
    @Autowired
    LocalizacionDataOnDemand OfertaDataOnDemand.localizacionDataOnDemand;
    
    @Autowired
    PuestoDataOnDemand OfertaDataOnDemand.puestoDataOnDemand;
    
    public Oferta OfertaDataOnDemand.getNewTransientOferta(int index) {
        Oferta obj = new Oferta();
        setEmpresa(obj, index);
        setFechaDisponibleFin(obj, index);
        setFechaDisponibleInicio(obj, index);
        setFechaInicioActividad(obj, index);
        setLocalizacion(obj, index);
        setOferta_estado(obj, index);
        setPerfil(obj, index);
        setSueldoBruto(obj, index);
        setTipologia(obj, index);
        setVacantes(obj, index);
        return obj;
    }
    
    public void OfertaDataOnDemand.setEmpresa(Oferta obj, int index) {
        Empresa empresa = empresaDataOnDemand.getRandomEmpresa();
        obj.setEmpresa(empresa);
    }
    
    public void OfertaDataOnDemand.setFechaDisponibleFin(Oferta obj, int index) {
        Date fechaDisponibleFin = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaDisponibleFin(fechaDisponibleFin);
    }
    
    public void OfertaDataOnDemand.setFechaDisponibleInicio(Oferta obj, int index) {
        Date fechaDisponibleInicio = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaDisponibleInicio(fechaDisponibleInicio);
    }
    
    public void OfertaDataOnDemand.setFechaInicioActividad(Oferta obj, int index) {
        Date fechaInicioActividad = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaInicioActividad(fechaInicioActividad);
    }
    
    public void OfertaDataOnDemand.setLocalizacion(Oferta obj, int index) {
        Localizacion localizacion = localizacionDataOnDemand.getRandomLocalizacion();
        obj.setLocalizacion(localizacion);
    }
    
    public void OfertaDataOnDemand.setOferta_estado(Oferta obj, int index) {
        OfertaEstado oferta_estado = OfertaEstado.class.getEnumConstants()[0];
        obj.setOferta_estado(oferta_estado);
    }
    
    public void OfertaDataOnDemand.setPerfil(Oferta obj, int index) {
        String perfil = "perfil_" + index;
        if (perfil.length() > 30) {
            perfil = perfil.substring(0, 30);
        }
        obj.setPerfil(perfil);
    }
    
    public void OfertaDataOnDemand.setSueldoBruto(Oferta obj, int index) {
        float sueldoBruto = new Integer(index).floatValue();
        obj.setSueldoBruto(sueldoBruto);
    }
    
    public void OfertaDataOnDemand.setTipologia(Oferta obj, int index) {
        String tipologia = "tipologia_" + index;
        if (tipologia.length() > 30) {
            tipologia = tipologia.substring(0, 30);
        }
        obj.setTipologia(tipologia);
    }
    
    public void OfertaDataOnDemand.setVacantes(Oferta obj, int index) {
        String vacantes = "vacantes_" + index;
        obj.setVacantes(vacantes);
    }
    
    public Oferta OfertaDataOnDemand.getSpecificOferta(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Oferta obj = data.get(index);
        Long id = obj.getId();
        return Oferta.findOferta(id);
    }
    
    public Oferta OfertaDataOnDemand.getRandomOferta() {
        init();
        Oferta obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Oferta.findOferta(id);
    }
    
    public boolean OfertaDataOnDemand.modifyOferta(Oferta obj) {
        return false;
    }
    
    public void OfertaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Oferta.findOfertaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Oferta' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Oferta>();
        for (int i = 0; i < 10; i++) {
            Oferta obj = getNewTransientOferta(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
