// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.findyourjob.domain;

import es.uca.iw.findyourjob.domain.Demandante;
import javax.persistence.Entity;

privileged aspect Demandante_Roo_Jpa_Entity {
    
    declare @type: Demandante: @Entity;
    
}
